export const VERIFYING_CREDENTIALS = "VERIFYING_CREDENTIALS";
export const VERIFY_CREDENTIALS_SUCCESS = "VERIFY_CREDENTIALS_SUCCESS";
export const VERIFY_CREDENTIALS_FAILURE = "VERIFY_CREDENTIALS_FAILURE";
export const LOADING_PLANETS = "LOADING_PLANETS";
export const LOAD_PLANETS_SUCCESS = "LOAD_PLANETS_SUCCESS";
export const LOAD_PLANETS_FAILURE = "LOAD_PLANETS_FAILURE";